name: Production Build Test
on:
 push:
   branches: [ main, master ]
 pull_request:
   branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: setup-node
       uses: actions/setup-node@v3
       with:
         node-version: 16
         cache: npm
     - name: npm-install
       run: npm i
     - name: Build 
       run: npm run build
